title:              Maraîchage en Wallonie
email:              /
description:        /
author:             Nicolas Biot
baseurl:            /
url:                https://github.com/biotnicolas

# Social Profiles
twitter_username:   /
github_username:    biotnicolas
facebook_username:  /
linkedin_username:  /

# Add your google-analytics ID here to activate google analytics
google_analytics:   / # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
